// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TestApp.Data;

#nullable disable

namespace TestApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251008005156_AddMockData")]
    partial class AddMockData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("TestApp.Models.Quote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("ValidQuotePeriod")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Quotes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Comments = "Special pricing",
                            CreatedDate = new DateTime(2025, 2, 5, 20, 51, 56, 529, DateTimeKind.Local).AddTicks(5350),
                            CustomerName = "Global Industries",
                            ProductName = "Custom Widget",
                            Quantity = 26,
                            Status = "Approved",
                            UnitPrice = 178.43m,
                            ValidQuotePeriod = new DateTime(2025, 2, 23, 20, 51, 56, 529, DateTimeKind.Local).AddTicks(5350)
                        },
                        new
                        {
                            Id = 2,
                            Comments = "Priority customer",
                            CreatedDate = new DateTime(2025, 8, 4, 20, 51, 56, 529, DateTimeKind.Local).AddTicks(5430),
                            CustomerName = "MegaCorp Ltd",
                            ProductName = "Standard Widget",
                            Quantity = 32,
                            Status = "Pending",
                            UnitPrice = 515.60m,
                            ValidQuotePeriod = new DateTime(2025, 10, 13, 20, 51, 56, 529, DateTimeKind.Local).AddTicks(5430)
                        },
                        new
                        {
                            Id = 3,
                            Comments = "First-time customer",
                            CreatedDate = new DateTime(2025, 4, 1, 20, 51, 56, 529, DateTimeKind.Local).AddTicks(5430),
                            CustomerName = "Kappa Corp",
                            ProductName = "Special Widget",
                            Quantity = 16,
                            Status = "Draft",
                            UnitPrice = 407.47m,
                            ValidQuotePeriod = new DateTime(2025, 4, 10, 20, 51, 56, 529, DateTimeKind.Local).AddTicks(5430)
                        },
                        new
                        {
                            Id = 4,
                            Comments = "Special pricing",
                            CreatedDate = new DateTime(2024, 12, 13, 20, 51, 56, 529, DateTimeKind.Local).AddTicks(5440),
                            CustomerName = "Acme Corp",
                            ProductName = "Ultra Widget",
                            Quantity = 90,
                            Status = "Approved",
                            UnitPrice = 157.76m,
                            ValidQuotePeriod = new DateTime(2025, 2, 2, 20, 51, 56, 529, DateTimeKind.Local).AddTicks(5440)
                        },
                        new
                        {
                            Id = 5,
                            Comments = "Emergency order",
                            CreatedDate = new DateTime(2025, 7, 31, 20, 51, 56, 529, DateTimeKind.Local).AddTicks(5440),
                            CustomerName = "Future Systems",
                            ProductName = "Special Widget",
                            Quantity = 1,
                            Status = "Approved",
                            UnitPrice = 831.07m,
                            ValidQuotePeriod = new DateTime(2025, 8, 10, 20, 51, 56, 529, DateTimeKind.Local).AddTicks(5440)
                        },
                        new
                        {
                            Id = 6,
                            Comments = "Rush delivery requested",
                            CreatedDate = new DateTime(2025, 1, 7, 20, 51, 56, 529, DateTimeKind.Local).AddTicks(5440),
                            CustomerName = "Global Industries",
                            ProductName = "Widget A",
                            Quantity = 78,
                            Status = "Approved",
                            UnitPrice = 61.01m,
                            ValidQuotePeriod = new DateTime(2025, 2, 14, 20, 51, 56, 529, DateTimeKind.Local).AddTicks(5440)
                        },
                        new
                        {
                            Id = 7,
                            Comments = "Special pricing",
                            CreatedDate = new DateTime(2025, 7, 8, 20, 51, 56, 529, DateTimeKind.Local).AddTicks(5450),
                            CustomerName = "Innovation Co",
                            ProductName = "Advanced Widget",
                            Quantity = 5,
                            Status = "Approved",
                            UnitPrice = 153.65m,
                            ValidQuotePeriod = new DateTime(2025, 9, 17, 20, 51, 56, 529, DateTimeKind.Local).AddTicks(5450)
                        },
                        new
                        {
                            Id = 8,
                            Comments = "Bulk discount applied",
                            CreatedDate = new DateTime(2025, 9, 18, 20, 51, 56, 529, DateTimeKind.Local).AddTicks(5450),
                            CustomerName = "Theta Group",
                            ProductName = "Advanced Widget",
                            Quantity = 2,
                            Status = "Pending",
                            UnitPrice = 228.45m,
                            ValidQuotePeriod = new DateTime(2025, 10, 29, 20, 51, 56, 529, DateTimeKind.Local).AddTicks(5450)
                        },
                        new
                        {
                            Id = 9,
                            Comments = "Special pricing",
                            CreatedDate = new DateTime(2025, 9, 12, 20, 51, 56, 529, DateTimeKind.Local).AddTicks(5450),
                            CustomerName = "Tech Solutions",
                            ProductName = "Enterprise Widget",
                            Quantity = 79,
                            Status = "Pending",
                            UnitPrice = 22.03m,
                            ValidQuotePeriod = new DateTime(2025, 11, 17, 20, 51, 56, 529, DateTimeKind.Local).AddTicks(5450)
                        },
                        new
                        {
                            Id = 10,
                            Comments = "",
                            CreatedDate = new DateTime(2025, 4, 8, 20, 51, 56, 529, DateTimeKind.Local).AddTicks(5450),
                            CustomerName = "Kappa Corp",
                            ProductName = "Widget A",
                            Quantity = 7,
                            Status = "Approved",
                            UnitPrice = 13.07m,
                            ValidQuotePeriod = new DateTime(2025, 4, 15, 20, 51, 56, 529, DateTimeKind.Local).AddTicks(5450)
                        },
                        new
                        {
                            Id = 11,
                            Comments = "Standard processing",
                            CreatedDate = new DateTime(2024, 11, 8, 20, 51, 56, 529, DateTimeKind.Local).AddTicks(5460),
                            CustomerName = "Gamma Corp",
                            ProductName = "Basic Widget",
                            Quantity = 5,
                            Status = "Pending",
                            UnitPrice = 626.61m,
                            ValidQuotePeriod = new DateTime(2025, 1, 31, 20, 51, 56, 529, DateTimeKind.Local).AddTicks(5460)
                        },
                        new
                        {
                            Id = 12,
                            Comments = "VIP customer",
                            CreatedDate = new DateTime(2025, 4, 30, 20, 51, 56, 529, DateTimeKind.Local).AddTicks(5460),
                            CustomerName = "Delta Enterprises",
                            ProductName = "Pro Widget",
                            Quantity = 90,
                            Status = "Approved",
                            UnitPrice = 307.37m,
                            ValidQuotePeriod = new DateTime(2025, 7, 11, 20, 51, 56, 529, DateTimeKind.Local).AddTicks(5460)
                        },
                        new
                        {
                            Id = 13,
                            Comments = "Expedited shipping",
                            CreatedDate = new DateTime(2025, 9, 29, 20, 51, 56, 529, DateTimeKind.Local).AddTicks(5460),
                            CustomerName = "Nu Technologies",
                            ProductName = "Deluxe Widget",
                            Quantity = 17,
                            Status = "Draft",
                            UnitPrice = 720.70m,
                            ValidQuotePeriod = new DateTime(2025, 12, 18, 20, 51, 56, 529, DateTimeKind.Local).AddTicks(5460)
                        },
                        new
                        {
                            Id = 14,
                            Comments = "New product line",
                            CreatedDate = new DateTime(2025, 6, 7, 20, 51, 56, 529, DateTimeKind.Local).AddTicks(5460),
                            CustomerName = "Global Industries",
                            ProductName = "Widget C",
                            Quantity = 59,
                            Status = "Approved",
                            UnitPrice = 225.66m,
                            ValidQuotePeriod = new DateTime(2025, 8, 17, 20, 51, 56, 529, DateTimeKind.Local).AddTicks(5460)
                        },
                        new
                        {
                            Id = 15,
                            Comments = "",
                            CreatedDate = new DateTime(2025, 1, 1, 20, 51, 56, 529, DateTimeKind.Local).AddTicks(5470),
                            CustomerName = "Theta Group",
                            ProductName = "Standard Widget",
                            Quantity = 98,
                            Status = "Approved",
                            UnitPrice = 562.06m,
                            ValidQuotePeriod = new DateTime(2025, 3, 4, 20, 51, 56, 529, DateTimeKind.Local).AddTicks(5470)
                        },
                        new
                        {
                            Id = 16,
                            Comments = "Volume discount",
                            CreatedDate = new DateTime(2025, 6, 3, 20, 51, 56, 529, DateTimeKind.Local).AddTicks(5470),
                            CustomerName = "Acme Corp",
                            ProductName = "Premium Widget",
                            Quantity = 4,
                            Status = "Draft",
                            UnitPrice = 275.44m,
                            ValidQuotePeriod = new DateTime(2025, 8, 26, 20, 51, 56, 529, DateTimeKind.Local).AddTicks(5470)
                        },
                        new
                        {
                            Id = 17,
                            Comments = "VIP customer",
                            CreatedDate = new DateTime(2025, 5, 6, 20, 51, 56, 529, DateTimeKind.Local).AddTicks(5470),
                            CustomerName = "Nu Technologies",
                            ProductName = "Widget C",
                            Quantity = 32,
                            Status = "Pending",
                            UnitPrice = 116.09m,
                            ValidQuotePeriod = new DateTime(2025, 5, 20, 20, 51, 56, 529, DateTimeKind.Local).AddTicks(5470)
                        },
                        new
                        {
                            Id = 18,
                            Comments = "Emergency order",
                            CreatedDate = new DateTime(2024, 12, 10, 20, 51, 56, 529, DateTimeKind.Local).AddTicks(5470),
                            CustomerName = "Acme Corp",
                            ProductName = "Giga Widget",
                            Quantity = 24,
                            Status = "Rejected",
                            UnitPrice = 905.89m,
                            ValidQuotePeriod = new DateTime(2024, 12, 17, 20, 51, 56, 529, DateTimeKind.Local).AddTicks(5470)
                        },
                        new
                        {
                            Id = 19,
                            Comments = "",
                            CreatedDate = new DateTime(2025, 6, 27, 20, 51, 56, 529, DateTimeKind.Local).AddTicks(5480),
                            CustomerName = "Zeta Manufacturing",
                            ProductName = "Advanced Widget",
                            Quantity = 30,
                            Status = "Draft",
                            UnitPrice = 202.31m,
                            ValidQuotePeriod = new DateTime(2025, 8, 18, 20, 51, 56, 529, DateTimeKind.Local).AddTicks(5480)
                        },
                        new
                        {
                            Id = 20,
                            Comments = "Bulk discount applied",
                            CreatedDate = new DateTime(2025, 7, 14, 20, 51, 56, 529, DateTimeKind.Local).AddTicks(5480),
                            CustomerName = "Nu Technologies",
                            ProductName = "Mega Widget",
                            Quantity = 88,
                            Status = "Draft",
                            UnitPrice = 145.22m,
                            ValidQuotePeriod = new DateTime(2025, 10, 6, 20, 51, 56, 529, DateTimeKind.Local).AddTicks(5480)
                        },
                        new
                        {
                            Id = 21,
                            Comments = "Expedited shipping",
                            CreatedDate = new DateTime(2025, 3, 17, 20, 51, 56, 529, DateTimeKind.Local).AddTicks(5480),
                            CustomerName = "Theta Group",
                            ProductName = "Widget C",
                            Quantity = 39,
                            Status = "Rejected",
                            UnitPrice = 608.18m,
                            ValidQuotePeriod = new DateTime(2025, 5, 9, 20, 51, 56, 529, DateTimeKind.Local).AddTicks(5480)
                        },
                        new
                        {
                            Id = 22,
                            Comments = "Rush delivery requested",
                            CreatedDate = new DateTime(2025, 6, 2, 20, 51, 56, 529, DateTimeKind.Local).AddTicks(5480),
                            CustomerName = "Gamma Corp",
                            ProductName = "Custom Widget",
                            Quantity = 81,
                            Status = "Draft",
                            UnitPrice = 957.74m,
                            ValidQuotePeriod = new DateTime(2025, 8, 27, 20, 51, 56, 529, DateTimeKind.Local).AddTicks(5480)
                        },
                        new
                        {
                            Id = 23,
                            Comments = "Rush delivery requested",
                            CreatedDate = new DateTime(2025, 10, 5, 20, 51, 56, 529, DateTimeKind.Local).AddTicks(5490),
                            CustomerName = "Mu Solutions",
                            ProductName = "Ultra Widget",
                            Quantity = 59,
                            Status = "Pending",
                            UnitPrice = 414.00m,
                            ValidQuotePeriod = new DateTime(2025, 10, 27, 20, 51, 56, 529, DateTimeKind.Local).AddTicks(5490)
                        },
                        new
                        {
                            Id = 24,
                            Comments = "New product line",
                            CreatedDate = new DateTime(2024, 11, 9, 20, 51, 56, 529, DateTimeKind.Local).AddTicks(5490),
                            CustomerName = "Lambda Industries",
                            ProductName = "Widget D",
                            Quantity = 54,
                            Status = "Approved",
                            UnitPrice = 343.88m,
                            ValidQuotePeriod = new DateTime(2025, 2, 4, 20, 51, 56, 529, DateTimeKind.Local).AddTicks(5490)
                        },
                        new
                        {
                            Id = 25,
                            Comments = "Regular customer",
                            CreatedDate = new DateTime(2024, 12, 11, 20, 51, 56, 529, DateTimeKind.Local).AddTicks(5490),
                            CustomerName = "Innovation Co",
                            ProductName = "Deluxe Widget",
                            Quantity = 80,
                            Status = "Draft",
                            UnitPrice = 535.59m,
                            ValidQuotePeriod = new DateTime(2025, 2, 18, 20, 51, 56, 529, DateTimeKind.Local).AddTicks(5490)
                        },
                        new
                        {
                            Id = 26,
                            Comments = "Expedited shipping",
                            CreatedDate = new DateTime(2025, 2, 7, 20, 51, 56, 529, DateTimeKind.Local).AddTicks(5500),
                            CustomerName = "Innovation Co",
                            ProductName = "Premium Widget",
                            Quantity = 64,
                            Status = "Draft",
                            UnitPrice = 843.62m,
                            ValidQuotePeriod = new DateTime(2025, 3, 1, 20, 51, 56, 529, DateTimeKind.Local).AddTicks(5500)
                        },
                        new
                        {
                            Id = 27,
                            Comments = "New product line",
                            CreatedDate = new DateTime(2024, 12, 17, 20, 51, 56, 529, DateTimeKind.Local).AddTicks(5500),
                            CustomerName = "Iota Systems",
                            ProductName = "Exa Widget",
                            Quantity = 47,
                            Status = "Rejected",
                            UnitPrice = 953.10m,
                            ValidQuotePeriod = new DateTime(2025, 3, 7, 20, 51, 56, 529, DateTimeKind.Local).AddTicks(5500)
                        },
                        new
                        {
                            Id = 28,
                            Comments = "Emergency order",
                            CreatedDate = new DateTime(2025, 8, 11, 20, 51, 56, 529, DateTimeKind.Local).AddTicks(5500),
                            CustomerName = "MegaCorp Ltd",
                            ProductName = "Advanced Widget",
                            Quantity = 71,
                            Status = "Draft",
                            UnitPrice = 510.90m,
                            ValidQuotePeriod = new DateTime(2025, 10, 5, 20, 51, 56, 529, DateTimeKind.Local).AddTicks(5500)
                        },
                        new
                        {
                            Id = 29,
                            Comments = "Standard processing",
                            CreatedDate = new DateTime(2025, 6, 2, 20, 51, 56, 529, DateTimeKind.Local).AddTicks(5500),
                            CustomerName = "Theta Group",
                            ProductName = "Premium Widget",
                            Quantity = 79,
                            Status = "Approved",
                            UnitPrice = 539.83m,
                            ValidQuotePeriod = new DateTime(2025, 7, 22, 20, 51, 56, 529, DateTimeKind.Local).AddTicks(5500)
                        },
                        new
                        {
                            Id = 30,
                            Comments = "Bulk discount applied",
                            CreatedDate = new DateTime(2024, 10, 31, 20, 51, 56, 529, DateTimeKind.Local).AddTicks(5510),
                            CustomerName = "Tech Solutions",
                            ProductName = "Premium Widget",
                            Quantity = 17,
                            Status = "Pending",
                            UnitPrice = 323.67m,
                            ValidQuotePeriod = new DateTime(2024, 11, 11, 20, 51, 56, 529, DateTimeKind.Local).AddTicks(5510)
                        },
                        new
                        {
                            Id = 31,
                            Comments = "Custom configuration",
                            CreatedDate = new DateTime(2024, 11, 19, 20, 51, 56, 529, DateTimeKind.Local).AddTicks(5510),
                            CustomerName = "Alpha Industries",
                            ProductName = "Enterprise Widget",
                            Quantity = 66,
                            Status = "Rejected",
                            UnitPrice = 773.41m,
                            ValidQuotePeriod = new DateTime(2025, 1, 4, 20, 51, 56, 529, DateTimeKind.Local).AddTicks(5510)
                        },
                        new
                        {
                            Id = 32,
                            Comments = "New product line",
                            CreatedDate = new DateTime(2024, 11, 29, 20, 51, 56, 529, DateTimeKind.Local).AddTicks(5510),
                            CustomerName = "StartUp Inc",
                            ProductName = "Peta Widget",
                            Quantity = 61,
                            Status = "Pending",
                            UnitPrice = 603.05m,
                            ValidQuotePeriod = new DateTime(2024, 12, 31, 20, 51, 56, 529, DateTimeKind.Local).AddTicks(5510)
                        },
                        new
                        {
                            Id = 33,
                            Comments = "",
                            CreatedDate = new DateTime(2025, 9, 8, 20, 51, 56, 529, DateTimeKind.Local).AddTicks(5510),
                            CustomerName = "Lambda Industries",
                            ProductName = "Deluxe Widget",
                            Quantity = 88,
                            Status = "Rejected",
                            UnitPrice = 929.34m,
                            ValidQuotePeriod = new DateTime(2025, 10, 24, 20, 51, 56, 529, DateTimeKind.Local).AddTicks(5510)
                        },
                        new
                        {
                            Id = 34,
                            Comments = "New product line",
                            CreatedDate = new DateTime(2025, 6, 20, 20, 51, 56, 529, DateTimeKind.Local).AddTicks(5520),
                            CustomerName = "Acme Corp",
                            ProductName = "Tera Widget",
                            Quantity = 67,
                            Status = "Approved",
                            UnitPrice = 420.93m,
                            ValidQuotePeriod = new DateTime(2025, 8, 14, 20, 51, 56, 529, DateTimeKind.Local).AddTicks(5520)
                        },
                        new
                        {
                            Id = 35,
                            Comments = "First-time customer",
                            CreatedDate = new DateTime(2025, 6, 21, 20, 51, 56, 529, DateTimeKind.Local).AddTicks(5520),
                            CustomerName = "Iota Systems",
                            ProductName = "Widget A",
                            Quantity = 66,
                            Status = "Draft",
                            UnitPrice = 350.80m,
                            ValidQuotePeriod = new DateTime(2025, 9, 14, 20, 51, 56, 529, DateTimeKind.Local).AddTicks(5520)
                        },
                        new
                        {
                            Id = 36,
                            Comments = "Bulk discount applied",
                            CreatedDate = new DateTime(2025, 3, 31, 20, 51, 56, 529, DateTimeKind.Local).AddTicks(5520),
                            CustomerName = "Future Systems",
                            ProductName = "Premium Widget",
                            Quantity = 64,
                            Status = "Approved",
                            UnitPrice = 615.14m,
                            ValidQuotePeriod = new DateTime(2025, 5, 7, 20, 51, 56, 529, DateTimeKind.Local).AddTicks(5520)
                        },
                        new
                        {
                            Id = 37,
                            Comments = "",
                            CreatedDate = new DateTime(2025, 2, 6, 20, 51, 56, 529, DateTimeKind.Local).AddTicks(5520),
                            CustomerName = "Global Industries",
                            ProductName = "Giga Widget",
                            Quantity = 97,
                            Status = "Pending",
                            UnitPrice = 300.87m,
                            ValidQuotePeriod = new DateTime(2025, 2, 21, 20, 51, 56, 529, DateTimeKind.Local).AddTicks(5520)
                        },
                        new
                        {
                            Id = 38,
                            Comments = "Standard processing",
                            CreatedDate = new DateTime(2025, 3, 10, 20, 51, 56, 529, DateTimeKind.Local).AddTicks(5530),
                            CustomerName = "StartUp Inc",
                            ProductName = "Widget D",
                            Quantity = 11,
                            Status = "Rejected",
                            UnitPrice = 653.95m,
                            ValidQuotePeriod = new DateTime(2025, 4, 15, 20, 51, 56, 529, DateTimeKind.Local).AddTicks(5530)
                        },
                        new
                        {
                            Id = 39,
                            Comments = "Expedited shipping",
                            CreatedDate = new DateTime(2025, 2, 10, 20, 51, 56, 529, DateTimeKind.Local).AddTicks(5530),
                            CustomerName = "Zeta Manufacturing",
                            ProductName = "Super Widget",
                            Quantity = 36,
                            Status = "Approved",
                            UnitPrice = 870.62m,
                            ValidQuotePeriod = new DateTime(2025, 3, 5, 20, 51, 56, 529, DateTimeKind.Local).AddTicks(5530)
                        },
                        new
                        {
                            Id = 40,
                            Comments = "Annual contract",
                            CreatedDate = new DateTime(2025, 5, 4, 20, 51, 56, 529, DateTimeKind.Local).AddTicks(5530),
                            CustomerName = "Iota Systems",
                            ProductName = "Special Widget",
                            Quantity = 67,
                            Status = "Pending",
                            UnitPrice = 547.53m,
                            ValidQuotePeriod = new DateTime(2025, 5, 27, 20, 51, 56, 529, DateTimeKind.Local).AddTicks(5530)
                        },
                        new
                        {
                            Id = 41,
                            Comments = "Bulk discount applied",
                            CreatedDate = new DateTime(2024, 10, 17, 20, 51, 56, 529, DateTimeKind.Local).AddTicks(5530),
                            CustomerName = "MegaCorp Ltd",
                            ProductName = "Deluxe Widget",
                            Quantity = 81,
                            Status = "Approved",
                            UnitPrice = 550.41m,
                            ValidQuotePeriod = new DateTime(2024, 12, 20, 20, 51, 56, 529, DateTimeKind.Local).AddTicks(5530)
                        },
                        new
                        {
                            Id = 42,
                            Comments = "Expedited shipping",
                            CreatedDate = new DateTime(2025, 3, 6, 20, 51, 56, 529, DateTimeKind.Local).AddTicks(5540),
                            CustomerName = "Gamma Corp",
                            ProductName = "Exa Widget",
                            Quantity = 86,
                            Status = "Draft",
                            UnitPrice = 511.81m,
                            ValidQuotePeriod = new DateTime(2025, 5, 14, 20, 51, 56, 529, DateTimeKind.Local).AddTicks(5540)
                        },
                        new
                        {
                            Id = 43,
                            Comments = "Bulk discount applied",
                            CreatedDate = new DateTime(2025, 5, 7, 20, 51, 56, 529, DateTimeKind.Local).AddTicks(5540),
                            CustomerName = "Epsilon Tech",
                            ProductName = "Pro Widget",
                            Quantity = 95,
                            Status = "Pending",
                            UnitPrice = 11.81m,
                            ValidQuotePeriod = new DateTime(2025, 5, 27, 20, 51, 56, 529, DateTimeKind.Local).AddTicks(5540)
                        },
                        new
                        {
                            Id = 44,
                            Comments = "Regular customer",
                            CreatedDate = new DateTime(2025, 4, 13, 20, 51, 56, 529, DateTimeKind.Local).AddTicks(5540),
                            CustomerName = "Beta Solutions",
                            ProductName = "Widget B",
                            Quantity = 79,
                            Status = "Pending",
                            UnitPrice = 198.40m,
                            ValidQuotePeriod = new DateTime(2025, 6, 18, 20, 51, 56, 529, DateTimeKind.Local).AddTicks(5540)
                        },
                        new
                        {
                            Id = 45,
                            Comments = "Emergency order",
                            CreatedDate = new DateTime(2024, 10, 29, 20, 51, 56, 529, DateTimeKind.Local).AddTicks(5540),
                            CustomerName = "MegaCorp Ltd",
                            ProductName = "Peta Widget",
                            Quantity = 63,
                            Status = "Approved",
                            UnitPrice = 892.95m,
                            ValidQuotePeriod = new DateTime(2024, 12, 16, 20, 51, 56, 529, DateTimeKind.Local).AddTicks(5540)
                        },
                        new
                        {
                            Id = 46,
                            Comments = "Volume discount",
                            CreatedDate = new DateTime(2025, 4, 6, 20, 51, 56, 529, DateTimeKind.Local).AddTicks(5550),
                            CustomerName = "Tech Solutions",
                            ProductName = "Widget C",
                            Quantity = 62,
                            Status = "Rejected",
                            UnitPrice = 914.71m,
                            ValidQuotePeriod = new DateTime(2025, 5, 9, 20, 51, 56, 529, DateTimeKind.Local).AddTicks(5550)
                        },
                        new
                        {
                            Id = 47,
                            Comments = "",
                            CreatedDate = new DateTime(2025, 8, 11, 20, 51, 56, 529, DateTimeKind.Local).AddTicks(5550),
                            CustomerName = "Global Industries",
                            ProductName = "Basic Widget",
                            Quantity = 1,
                            Status = "Approved",
                            UnitPrice = 119.46m,
                            ValidQuotePeriod = new DateTime(2025, 9, 18, 20, 51, 56, 529, DateTimeKind.Local).AddTicks(5550)
                        },
                        new
                        {
                            Id = 48,
                            Comments = "VIP customer",
                            CreatedDate = new DateTime(2025, 7, 13, 20, 51, 56, 529, DateTimeKind.Local).AddTicks(5550),
                            CustomerName = "Kappa Corp",
                            ProductName = "Giga Widget",
                            Quantity = 60,
                            Status = "Draft",
                            UnitPrice = 408.96m,
                            ValidQuotePeriod = new DateTime(2025, 10, 4, 20, 51, 56, 529, DateTimeKind.Local).AddTicks(5550)
                        },
                        new
                        {
                            Id = 49,
                            Comments = "VIP customer",
                            CreatedDate = new DateTime(2025, 6, 24, 20, 51, 56, 529, DateTimeKind.Local).AddTicks(5550),
                            CustomerName = "Tech Solutions",
                            ProductName = "Widget A",
                            Quantity = 10,
                            Status = "Approved",
                            UnitPrice = 661.01m,
                            ValidQuotePeriod = new DateTime(2025, 8, 15, 20, 51, 56, 529, DateTimeKind.Local).AddTicks(5550)
                        },
                        new
                        {
                            Id = 50,
                            Comments = "Emergency order",
                            CreatedDate = new DateTime(2025, 3, 30, 20, 51, 56, 529, DateTimeKind.Local).AddTicks(5560),
                            CustomerName = "Mu Solutions",
                            ProductName = "Super Widget",
                            Quantity = 35,
                            Status = "Pending",
                            UnitPrice = 899.82m,
                            ValidQuotePeriod = new DateTime(2025, 6, 4, 20, 51, 56, 529, DateTimeKind.Local).AddTicks(5560)
                        },
                        new
                        {
                            Id = 51,
                            Comments = "New product line",
                            CreatedDate = new DateTime(2024, 12, 21, 20, 51, 56, 529, DateTimeKind.Local).AddTicks(5560),
                            CustomerName = "Mu Solutions",
                            ProductName = "Giga Widget",
                            Quantity = 9,
                            Status = "Rejected",
                            UnitPrice = 672.70m,
                            ValidQuotePeriod = new DateTime(2025, 3, 8, 20, 51, 56, 529, DateTimeKind.Local).AddTicks(5560)
                        },
                        new
                        {
                            Id = 52,
                            Comments = "Regular customer",
                            CreatedDate = new DateTime(2024, 12, 2, 20, 51, 56, 529, DateTimeKind.Local).AddTicks(5560),
                            CustomerName = "Theta Group",
                            ProductName = "Exa Widget",
                            Quantity = 81,
                            Status = "Pending",
                            UnitPrice = 816.31m,
                            ValidQuotePeriod = new DateTime(2024, 12, 24, 20, 51, 56, 529, DateTimeKind.Local).AddTicks(5560)
                        },
                        new
                        {
                            Id = 53,
                            Comments = "",
                            CreatedDate = new DateTime(2025, 7, 27, 20, 51, 56, 529, DateTimeKind.Local).AddTicks(5560),
                            CustomerName = "Kappa Corp",
                            ProductName = "Basic Widget",
                            Quantity = 91,
                            Status = "Rejected",
                            UnitPrice = 585.33m,
                            ValidQuotePeriod = new DateTime(2025, 8, 25, 20, 51, 56, 529, DateTimeKind.Local).AddTicks(5560)
                        },
                        new
                        {
                            Id = 54,
                            Comments = "Regular customer",
                            CreatedDate = new DateTime(2024, 12, 2, 20, 51, 56, 529, DateTimeKind.Local).AddTicks(5570),
                            CustomerName = "Lambda Industries",
                            ProductName = "Basic Widget",
                            Quantity = 97,
                            Status = "Draft",
                            UnitPrice = 113.83m,
                            ValidQuotePeriod = new DateTime(2025, 1, 6, 20, 51, 56, 529, DateTimeKind.Local).AddTicks(5570)
                        },
                        new
                        {
                            Id = 55,
                            Comments = "Standard processing",
                            CreatedDate = new DateTime(2025, 4, 3, 20, 51, 56, 529, DateTimeKind.Local).AddTicks(5570),
                            CustomerName = "Acme Corp",
                            ProductName = "Special Widget",
                            Quantity = 32,
                            Status = "Draft",
                            UnitPrice = 666.72m,
                            ValidQuotePeriod = new DateTime(2025, 6, 29, 20, 51, 56, 529, DateTimeKind.Local).AddTicks(5570)
                        },
                        new
                        {
                            Id = 56,
                            Comments = "First-time customer",
                            CreatedDate = new DateTime(2025, 1, 8, 20, 51, 56, 529, DateTimeKind.Local).AddTicks(5570),
                            CustomerName = "StartUp Inc",
                            ProductName = "Enterprise Widget",
                            Quantity = 56,
                            Status = "Rejected",
                            UnitPrice = 392.30m,
                            ValidQuotePeriod = new DateTime(2025, 1, 24, 20, 51, 56, 529, DateTimeKind.Local).AddTicks(5570)
                        },
                        new
                        {
                            Id = 57,
                            Comments = "Regular customer",
                            CreatedDate = new DateTime(2025, 6, 28, 20, 51, 56, 529, DateTimeKind.Local).AddTicks(5570),
                            CustomerName = "Gamma Corp",
                            ProductName = "Advanced Widget",
                            Quantity = 5,
                            Status = "Pending",
                            UnitPrice = 541.63m,
                            ValidQuotePeriod = new DateTime(2025, 9, 25, 20, 51, 56, 529, DateTimeKind.Local).AddTicks(5570)
                        },
                        new
                        {
                            Id = 58,
                            Comments = "Regular customer",
                            CreatedDate = new DateTime(2024, 11, 3, 20, 51, 56, 529, DateTimeKind.Local).AddTicks(5580),
                            CustomerName = "Nu Technologies",
                            ProductName = "Deluxe Widget",
                            Quantity = 41,
                            Status = "Rejected",
                            UnitPrice = 249.17m,
                            ValidQuotePeriod = new DateTime(2025, 1, 22, 20, 51, 56, 529, DateTimeKind.Local).AddTicks(5580)
                        },
                        new
                        {
                            Id = 59,
                            Comments = "Regular customer",
                            CreatedDate = new DateTime(2025, 9, 17, 20, 51, 56, 529, DateTimeKind.Local).AddTicks(5580),
                            CustomerName = "Gamma Corp",
                            ProductName = "Giga Widget",
                            Quantity = 89,
                            Status = "Pending",
                            UnitPrice = 793.41m,
                            ValidQuotePeriod = new DateTime(2025, 12, 1, 20, 51, 56, 529, DateTimeKind.Local).AddTicks(5580)
                        },
                        new
                        {
                            Id = 60,
                            Comments = "Bulk discount applied",
                            CreatedDate = new DateTime(2025, 8, 16, 20, 51, 56, 529, DateTimeKind.Local).AddTicks(5580),
                            CustomerName = "Zeta Manufacturing",
                            ProductName = "Enterprise Widget",
                            Quantity = 45,
                            Status = "Approved",
                            UnitPrice = 775.27m,
                            ValidQuotePeriod = new DateTime(2025, 10, 13, 20, 51, 56, 529, DateTimeKind.Local).AddTicks(5580)
                        },
                        new
                        {
                            Id = 61,
                            Comments = "Special pricing",
                            CreatedDate = new DateTime(2025, 5, 26, 20, 51, 56, 529, DateTimeKind.Local).AddTicks(5580),
                            CustomerName = "Global Industries",
                            ProductName = "Widget C",
                            Quantity = 51,
                            Status = "Pending",
                            UnitPrice = 504.19m,
                            ValidQuotePeriod = new DateTime(2025, 6, 13, 20, 51, 56, 529, DateTimeKind.Local).AddTicks(5580)
                        },
                        new
                        {
                            Id = 62,
                            Comments = "Custom configuration",
                            CreatedDate = new DateTime(2025, 1, 30, 20, 51, 56, 529, DateTimeKind.Local).AddTicks(5590),
                            CustomerName = "Zeta Manufacturing",
                            ProductName = "Mega Widget",
                            Quantity = 81,
                            Status = "Rejected",
                            UnitPrice = 363.23m,
                            ValidQuotePeriod = new DateTime(2025, 2, 18, 20, 51, 56, 529, DateTimeKind.Local).AddTicks(5590)
                        },
                        new
                        {
                            Id = 63,
                            Comments = "Custom configuration",
                            CreatedDate = new DateTime(2025, 6, 25, 20, 51, 56, 529, DateTimeKind.Local).AddTicks(5590),
                            CustomerName = "Beta Solutions",
                            ProductName = "Special Widget",
                            Quantity = 15,
                            Status = "Rejected",
                            UnitPrice = 120.13m,
                            ValidQuotePeriod = new DateTime(2025, 7, 25, 20, 51, 56, 529, DateTimeKind.Local).AddTicks(5590)
                        },
                        new
                        {
                            Id = 64,
                            Comments = "Special pricing",
                            CreatedDate = new DateTime(2025, 1, 9, 20, 51, 56, 529, DateTimeKind.Local).AddTicks(5590),
                            CustomerName = "Gamma Corp",
                            ProductName = "Peta Widget",
                            Quantity = 82,
                            Status = "Draft",
                            UnitPrice = 440.13m,
                            ValidQuotePeriod = new DateTime(2025, 3, 7, 20, 51, 56, 529, DateTimeKind.Local).AddTicks(5590)
                        },
                        new
                        {
                            Id = 65,
                            Comments = "Volume discount",
                            CreatedDate = new DateTime(2025, 7, 24, 20, 51, 56, 529, DateTimeKind.Local).AddTicks(5590),
                            CustomerName = "Mu Solutions",
                            ProductName = "Widget B",
                            Quantity = 72,
                            Status = "Pending",
                            UnitPrice = 304.65m,
                            ValidQuotePeriod = new DateTime(2025, 9, 25, 20, 51, 56, 529, DateTimeKind.Local).AddTicks(5590)
                        },
                        new
                        {
                            Id = 66,
                            Comments = "Bulk discount applied",
                            CreatedDate = new DateTime(2025, 4, 16, 20, 51, 56, 529, DateTimeKind.Local).AddTicks(5600),
                            CustomerName = "StartUp Inc",
                            ProductName = "Advanced Widget",
                            Quantity = 48,
                            Status = "Approved",
                            UnitPrice = 272.61m,
                            ValidQuotePeriod = new DateTime(2025, 7, 13, 20, 51, 56, 529, DateTimeKind.Local).AddTicks(5600)
                        },
                        new
                        {
                            Id = 67,
                            Comments = "Priority customer",
                            CreatedDate = new DateTime(2025, 2, 8, 20, 51, 56, 529, DateTimeKind.Local).AddTicks(5600),
                            CustomerName = "StartUp Inc",
                            ProductName = "Enterprise Widget",
                            Quantity = 13,
                            Status = "Draft",
                            UnitPrice = 54.29m,
                            ValidQuotePeriod = new DateTime(2025, 3, 9, 20, 51, 56, 529, DateTimeKind.Local).AddTicks(5600)
                        },
                        new
                        {
                            Id = 68,
                            Comments = "Emergency order",
                            CreatedDate = new DateTime(2025, 7, 21, 20, 51, 56, 529, DateTimeKind.Local).AddTicks(5600),
                            CustomerName = "Alpha Industries",
                            ProductName = "Tera Widget",
                            Quantity = 44,
                            Status = "Draft",
                            UnitPrice = 45.25m,
                            ValidQuotePeriod = new DateTime(2025, 9, 26, 20, 51, 56, 529, DateTimeKind.Local).AddTicks(5600)
                        },
                        new
                        {
                            Id = 69,
                            Comments = "Volume discount",
                            CreatedDate = new DateTime(2025, 9, 21, 20, 51, 56, 529, DateTimeKind.Local).AddTicks(5610),
                            CustomerName = "Epsilon Tech",
                            ProductName = "Super Widget",
                            Quantity = 86,
                            Status = "Draft",
                            UnitPrice = 876.37m,
                            ValidQuotePeriod = new DateTime(2025, 10, 10, 20, 51, 56, 529, DateTimeKind.Local).AddTicks(5610)
                        },
                        new
                        {
                            Id = 70,
                            Comments = "Bulk discount applied",
                            CreatedDate = new DateTime(2024, 11, 12, 20, 51, 56, 529, DateTimeKind.Local).AddTicks(5630),
                            CustomerName = "Tech Solutions",
                            ProductName = "Widget C",
                            Quantity = 30,
                            Status = "Draft",
                            UnitPrice = 999.59m,
                            ValidQuotePeriod = new DateTime(2025, 1, 30, 20, 51, 56, 529, DateTimeKind.Local).AddTicks(5630)
                        },
                        new
                        {
                            Id = 71,
                            Comments = "Rush delivery requested",
                            CreatedDate = new DateTime(2025, 9, 8, 20, 51, 56, 529, DateTimeKind.Local).AddTicks(5630),
                            CustomerName = "MegaCorp Ltd",
                            ProductName = "Widget D",
                            Quantity = 63,
                            Status = "Pending",
                            UnitPrice = 658.88m,
                            ValidQuotePeriod = new DateTime(2025, 9, 27, 20, 51, 56, 529, DateTimeKind.Local).AddTicks(5630)
                        },
                        new
                        {
                            Id = 72,
                            Comments = "",
                            CreatedDate = new DateTime(2025, 4, 4, 20, 51, 56, 529, DateTimeKind.Local).AddTicks(5630),
                            CustomerName = "Lambda Industries",
                            ProductName = "Special Widget",
                            Quantity = 49,
                            Status = "Approved",
                            UnitPrice = 366.35m,
                            ValidQuotePeriod = new DateTime(2025, 6, 10, 20, 51, 56, 529, DateTimeKind.Local).AddTicks(5630)
                        },
                        new
                        {
                            Id = 73,
                            Comments = "Emergency order",
                            CreatedDate = new DateTime(2024, 10, 27, 20, 51, 56, 529, DateTimeKind.Local).AddTicks(5630),
                            CustomerName = "Epsilon Tech",
                            ProductName = "Widget C",
                            Quantity = 85,
                            Status = "Pending",
                            UnitPrice = 914.10m,
                            ValidQuotePeriod = new DateTime(2024, 11, 27, 20, 51, 56, 529, DateTimeKind.Local).AddTicks(5630)
                        },
                        new
                        {
                            Id = 74,
                            Comments = "Regular customer",
                            CreatedDate = new DateTime(2025, 7, 14, 20, 51, 56, 529, DateTimeKind.Local).AddTicks(5640),
                            CustomerName = "Epsilon Tech",
                            ProductName = "Widget D",
                            Quantity = 5,
                            Status = "Draft",
                            UnitPrice = 57.30m,
                            ValidQuotePeriod = new DateTime(2025, 9, 9, 20, 51, 56, 529, DateTimeKind.Local).AddTicks(5640)
                        },
                        new
                        {
                            Id = 75,
                            Comments = "Expedited shipping",
                            CreatedDate = new DateTime(2025, 3, 1, 20, 51, 56, 529, DateTimeKind.Local).AddTicks(5640),
                            CustomerName = "Kappa Corp",
                            ProductName = "Tera Widget",
                            Quantity = 88,
                            Status = "Draft",
                            UnitPrice = 202.45m,
                            ValidQuotePeriod = new DateTime(2025, 3, 15, 20, 51, 56, 529, DateTimeKind.Local).AddTicks(5640)
                        },
                        new
                        {
                            Id = 76,
                            Comments = "Expedited shipping",
                            CreatedDate = new DateTime(2025, 1, 15, 20, 51, 56, 529, DateTimeKind.Local).AddTicks(5640),
                            CustomerName = "StartUp Inc",
                            ProductName = "Widget C",
                            Quantity = 48,
                            Status = "Draft",
                            UnitPrice = 986.19m,
                            ValidQuotePeriod = new DateTime(2025, 3, 3, 20, 51, 56, 529, DateTimeKind.Local).AddTicks(5640)
                        },
                        new
                        {
                            Id = 77,
                            Comments = "Priority customer",
                            CreatedDate = new DateTime(2025, 5, 28, 20, 51, 56, 529, DateTimeKind.Local).AddTicks(5640),
                            CustomerName = "StartUp Inc",
                            ProductName = "Super Widget",
                            Quantity = 2,
                            Status = "Pending",
                            UnitPrice = 719.89m,
                            ValidQuotePeriod = new DateTime(2025, 6, 7, 20, 51, 56, 529, DateTimeKind.Local).AddTicks(5640)
                        },
                        new
                        {
                            Id = 78,
                            Comments = "Expedited shipping",
                            CreatedDate = new DateTime(2025, 1, 28, 20, 51, 56, 529, DateTimeKind.Local).AddTicks(5650),
                            CustomerName = "Mu Solutions",
                            ProductName = "Widget A",
                            Quantity = 25,
                            Status = "Draft",
                            UnitPrice = 55.64m,
                            ValidQuotePeriod = new DateTime(2025, 3, 13, 20, 51, 56, 529, DateTimeKind.Local).AddTicks(5650)
                        },
                        new
                        {
                            Id = 79,
                            Comments = "",
                            CreatedDate = new DateTime(2025, 4, 12, 20, 51, 56, 529, DateTimeKind.Local).AddTicks(5650),
                            CustomerName = "Nu Technologies",
                            ProductName = "Standard Widget",
                            Quantity = 62,
                            Status = "Rejected",
                            UnitPrice = 684.96m,
                            ValidQuotePeriod = new DateTime(2025, 7, 8, 20, 51, 56, 529, DateTimeKind.Local).AddTicks(5650)
                        },
                        new
                        {
                            Id = 80,
                            Comments = "VIP customer",
                            CreatedDate = new DateTime(2025, 9, 8, 20, 51, 56, 529, DateTimeKind.Local).AddTicks(5650),
                            CustomerName = "Alpha Industries",
                            ProductName = "Pro Widget",
                            Quantity = 32,
                            Status = "Rejected",
                            UnitPrice = 700.89m,
                            ValidQuotePeriod = new DateTime(2025, 9, 29, 20, 51, 56, 529, DateTimeKind.Local).AddTicks(5650)
                        },
                        new
                        {
                            Id = 81,
                            Comments = "Volume discount",
                            CreatedDate = new DateTime(2025, 5, 12, 20, 51, 56, 529, DateTimeKind.Local).AddTicks(5650),
                            CustomerName = "Kappa Corp",
                            ProductName = "Widget A",
                            Quantity = 54,
                            Status = "Draft",
                            UnitPrice = 880.29m,
                            ValidQuotePeriod = new DateTime(2025, 6, 1, 20, 51, 56, 529, DateTimeKind.Local).AddTicks(5650)
                        },
                        new
                        {
                            Id = 82,
                            Comments = "Special pricing",
                            CreatedDate = new DateTime(2025, 1, 14, 20, 51, 56, 529, DateTimeKind.Local).AddTicks(5660),
                            CustomerName = "StartUp Inc",
                            ProductName = "Ultra Widget",
                            Quantity = 18,
                            Status = "Pending",
                            UnitPrice = 970.20m,
                            ValidQuotePeriod = new DateTime(2025, 3, 10, 20, 51, 56, 529, DateTimeKind.Local).AddTicks(5660)
                        },
                        new
                        {
                            Id = 83,
                            Comments = "VIP customer",
                            CreatedDate = new DateTime(2025, 4, 23, 20, 51, 56, 529, DateTimeKind.Local).AddTicks(5660),
                            CustomerName = "Eta Services",
                            ProductName = "Widget A",
                            Quantity = 94,
                            Status = "Approved",
                            UnitPrice = 522.79m,
                            ValidQuotePeriod = new DateTime(2025, 6, 27, 20, 51, 56, 529, DateTimeKind.Local).AddTicks(5660)
                        },
                        new
                        {
                            Id = 84,
                            Comments = "Custom configuration",
                            CreatedDate = new DateTime(2025, 7, 27, 20, 51, 56, 529, DateTimeKind.Local).AddTicks(5660),
                            CustomerName = "Zeta Manufacturing",
                            ProductName = "Custom Widget",
                            Quantity = 95,
                            Status = "Approved",
                            UnitPrice = 642.15m,
                            ValidQuotePeriod = new DateTime(2025, 8, 12, 20, 51, 56, 529, DateTimeKind.Local).AddTicks(5660)
                        },
                        new
                        {
                            Id = 85,
                            Comments = "New product line",
                            CreatedDate = new DateTime(2025, 2, 21, 20, 51, 56, 529, DateTimeKind.Local).AddTicks(5660),
                            CustomerName = "Zeta Manufacturing",
                            ProductName = "Tera Widget",
                            Quantity = 3,
                            Status = "Approved",
                            UnitPrice = 446.49m,
                            ValidQuotePeriod = new DateTime(2025, 3, 13, 20, 51, 56, 529, DateTimeKind.Local).AddTicks(5660)
                        },
                        new
                        {
                            Id = 86,
                            Comments = "Regular customer",
                            CreatedDate = new DateTime(2025, 1, 3, 20, 51, 56, 529, DateTimeKind.Local).AddTicks(5670),
                            CustomerName = "Delta Enterprises",
                            ProductName = "Widget B",
                            Quantity = 10,
                            Status = "Draft",
                            UnitPrice = 438.48m,
                            ValidQuotePeriod = new DateTime(2025, 2, 10, 20, 51, 56, 529, DateTimeKind.Local).AddTicks(5670)
                        },
                        new
                        {
                            Id = 87,
                            Comments = "Expedited shipping",
                            CreatedDate = new DateTime(2024, 12, 19, 20, 51, 56, 529, DateTimeKind.Local).AddTicks(5670),
                            CustomerName = "Nu Technologies",
                            ProductName = "Exa Widget",
                            Quantity = 81,
                            Status = "Draft",
                            UnitPrice = 673.06m,
                            ValidQuotePeriod = new DateTime(2025, 3, 11, 20, 51, 56, 529, DateTimeKind.Local).AddTicks(5670)
                        },
                        new
                        {
                            Id = 88,
                            Comments = "VIP customer",
                            CreatedDate = new DateTime(2025, 5, 5, 20, 51, 56, 529, DateTimeKind.Local).AddTicks(5670),
                            CustomerName = "Kappa Corp",
                            ProductName = "Mega Widget",
                            Quantity = 67,
                            Status = "Rejected",
                            UnitPrice = 928.18m,
                            ValidQuotePeriod = new DateTime(2025, 5, 18, 20, 51, 56, 529, DateTimeKind.Local).AddTicks(5670)
                        },
                        new
                        {
                            Id = 89,
                            Comments = "Expedited shipping",
                            CreatedDate = new DateTime(2025, 9, 17, 20, 51, 56, 529, DateTimeKind.Local).AddTicks(5670),
                            CustomerName = "Global Industries",
                            ProductName = "Mega Widget",
                            Quantity = 49,
                            Status = "Draft",
                            UnitPrice = 551.29m,
                            ValidQuotePeriod = new DateTime(2025, 12, 1, 20, 51, 56, 529, DateTimeKind.Local).AddTicks(5670)
                        },
                        new
                        {
                            Id = 90,
                            Comments = "Rush delivery requested",
                            CreatedDate = new DateTime(2025, 8, 27, 20, 51, 56, 529, DateTimeKind.Local).AddTicks(5680),
                            CustomerName = "MegaCorp Ltd",
                            ProductName = "Widget C",
                            Quantity = 65,
                            Status = "Pending",
                            UnitPrice = 426.26m,
                            ValidQuotePeriod = new DateTime(2025, 10, 31, 20, 51, 56, 529, DateTimeKind.Local).AddTicks(5680)
                        },
                        new
                        {
                            Id = 91,
                            Comments = "Emergency order",
                            CreatedDate = new DateTime(2025, 10, 3, 20, 51, 56, 529, DateTimeKind.Local).AddTicks(5680),
                            CustomerName = "Theta Group",
                            ProductName = "Ultra Widget",
                            Quantity = 54,
                            Status = "Approved",
                            UnitPrice = 1006.30m,
                            ValidQuotePeriod = new DateTime(2025, 12, 8, 20, 51, 56, 529, DateTimeKind.Local).AddTicks(5680)
                        },
                        new
                        {
                            Id = 92,
                            Comments = "Rush delivery requested",
                            CreatedDate = new DateTime(2024, 11, 3, 20, 51, 56, 529, DateTimeKind.Local).AddTicks(5680),
                            CustomerName = "Gamma Corp",
                            ProductName = "Basic Widget",
                            Quantity = 83,
                            Status = "Draft",
                            UnitPrice = 227.56m,
                            ValidQuotePeriod = new DateTime(2024, 11, 24, 20, 51, 56, 529, DateTimeKind.Local).AddTicks(5680)
                        },
                        new
                        {
                            Id = 93,
                            Comments = "Bulk discount applied",
                            CreatedDate = new DateTime(2025, 5, 7, 20, 51, 56, 529, DateTimeKind.Local).AddTicks(5680),
                            CustomerName = "Acme Corp",
                            ProductName = "Advanced Widget",
                            Quantity = 31,
                            Status = "Pending",
                            UnitPrice = 990.52m,
                            ValidQuotePeriod = new DateTime(2025, 7, 15, 20, 51, 56, 529, DateTimeKind.Local).AddTicks(5680)
                        },
                        new
                        {
                            Id = 94,
                            Comments = "VIP customer",
                            CreatedDate = new DateTime(2024, 11, 23, 20, 51, 56, 529, DateTimeKind.Local).AddTicks(5690),
                            CustomerName = "Lambda Industries",
                            ProductName = "Exa Widget",
                            Quantity = 11,
                            Status = "Draft",
                            UnitPrice = 578.37m,
                            ValidQuotePeriod = new DateTime(2025, 1, 12, 20, 51, 56, 529, DateTimeKind.Local).AddTicks(5690)
                        },
                        new
                        {
                            Id = 95,
                            Comments = "Special pricing",
                            CreatedDate = new DateTime(2024, 12, 31, 20, 51, 56, 529, DateTimeKind.Local).AddTicks(5690),
                            CustomerName = "Theta Group",
                            ProductName = "Premium Widget",
                            Quantity = 24,
                            Status = "Rejected",
                            UnitPrice = 942.46m,
                            ValidQuotePeriod = new DateTime(2025, 3, 7, 20, 51, 56, 529, DateTimeKind.Local).AddTicks(5690)
                        },
                        new
                        {
                            Id = 96,
                            Comments = "Bulk discount applied",
                            CreatedDate = new DateTime(2025, 8, 27, 20, 51, 56, 529, DateTimeKind.Local).AddTicks(5690),
                            CustomerName = "Lambda Industries",
                            ProductName = "Basic Widget",
                            Quantity = 68,
                            Status = "Draft",
                            UnitPrice = 45.20m,
                            ValidQuotePeriod = new DateTime(2025, 9, 28, 20, 51, 56, 529, DateTimeKind.Local).AddTicks(5690)
                        },
                        new
                        {
                            Id = 97,
                            Comments = "First-time customer",
                            CreatedDate = new DateTime(2025, 2, 5, 20, 51, 56, 529, DateTimeKind.Local).AddTicks(5690),
                            CustomerName = "Theta Group",
                            ProductName = "Super Widget",
                            Quantity = 70,
                            Status = "Draft",
                            UnitPrice = 627.66m,
                            ValidQuotePeriod = new DateTime(2025, 2, 24, 20, 51, 56, 529, DateTimeKind.Local).AddTicks(5690)
                        },
                        new
                        {
                            Id = 98,
                            Comments = "Emergency order",
                            CreatedDate = new DateTime(2025, 6, 1, 20, 51, 56, 529, DateTimeKind.Local).AddTicks(5700),
                            CustomerName = "Kappa Corp",
                            ProductName = "Enterprise Widget",
                            Quantity = 75,
                            Status = "Draft",
                            UnitPrice = 675.32m,
                            ValidQuotePeriod = new DateTime(2025, 7, 13, 20, 51, 56, 529, DateTimeKind.Local).AddTicks(5700)
                        },
                        new
                        {
                            Id = 99,
                            Comments = "Standard processing",
                            CreatedDate = new DateTime(2025, 8, 18, 20, 51, 56, 529, DateTimeKind.Local).AddTicks(5700),
                            CustomerName = "Epsilon Tech",
                            ProductName = "Custom Widget",
                            Quantity = 83,
                            Status = "Draft",
                            UnitPrice = 99.20m,
                            ValidQuotePeriod = new DateTime(2025, 10, 20, 20, 51, 56, 529, DateTimeKind.Local).AddTicks(5700)
                        },
                        new
                        {
                            Id = 100,
                            Comments = "Standard processing",
                            CreatedDate = new DateTime(2024, 10, 19, 20, 51, 56, 529, DateTimeKind.Local).AddTicks(5700),
                            CustomerName = "Gamma Corp",
                            ProductName = "Super Widget",
                            Quantity = 99,
                            Status = "Pending",
                            UnitPrice = 455.57m,
                            ValidQuotePeriod = new DateTime(2024, 12, 8, 20, 51, 56, 529, DateTimeKind.Local).AddTicks(5700)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
