// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TestApp.Data;

#nullable disable

namespace TestApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("TestApp.Models.Quote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("ValidQuotePeriod")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Quotes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Comments = "Customer requested rush delivery",
                            CreatedDate = new DateTime(2025, 10, 1, 23, 50, 41, 485, DateTimeKind.Local).AddTicks(7320),
                            CustomerName = "Acme Corp",
                            ProductName = "Widget A",
                            Quantity = 10,
                            Status = "Draft",
                            UnitPrice = 25.00m,
                            ValidQuotePeriod = new DateTime(2025, 10, 11, 23, 50, 41, 485, DateTimeKind.Local).AddTicks(7370)
                        },
                        new
                        {
                            Id = 2,
                            Comments = "",
                            CreatedDate = new DateTime(2025, 10, 3, 23, 50, 41, 485, DateTimeKind.Local).AddTicks(7380),
                            CustomerName = "Tech Solutions",
                            ProductName = "Widget B",
                            Quantity = 5,
                            Status = "Pending",
                            UnitPrice = 45.50m,
                            ValidQuotePeriod = new DateTime(2025, 11, 2, 23, 50, 41, 485, DateTimeKind.Local).AddTicks(7380)
                        },
                        new
                        {
                            Id = 3,
                            Comments = "",
                            CreatedDate = new DateTime(2025, 10, 5, 23, 50, 41, 485, DateTimeKind.Local).AddTicks(7380),
                            CustomerName = "Global Industries",
                            ProductName = "Widget C",
                            Quantity = 20,
                            Status = "Approved",
                            UnitPrice = 15.75m,
                            ValidQuotePeriod = new DateTime(2025, 11, 4, 23, 50, 41, 485, DateTimeKind.Local).AddTicks(7380)
                        },
                        new
                        {
                            Id = 4,
                            Comments = "",
                            CreatedDate = new DateTime(2025, 10, 4, 23, 50, 41, 485, DateTimeKind.Local).AddTicks(7380),
                            CustomerName = "StartUp Inc",
                            ProductName = "Widget D",
                            Quantity = 8,
                            Status = "Draft",
                            UnitPrice = 35.25m,
                            ValidQuotePeriod = new DateTime(2025, 10, 5, 23, 50, 41, 485, DateTimeKind.Local).AddTicks(7390)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
